@startuml


class Venda{
    - data: LocalDate
    + getTotal()
}

class Item{
    - quantidade: int
    - getValorTotal()
}

class Produto{
    - MIN_CARACTERES_DESCRICAO:int = 3
    - MIN_MARGEM_LUCRO:double = 0.3
    - MAX_MARGEM_LUCRO:double = 0.8
    - IMPOSTO:double = 0.18
    - descricao: string
    - precoCusto: double
    - precoVenda: double
    - margemLucro: double
    + getValorImposto()
    + getValorTotal()
}

class Estoque{
    - relatorioProdutosEmFalta()
}

class Inventario{
    - quantidadeMinima: int
    - produto: Produto
    - QuantidadeDisponivel: int
    + getDisponibilidade()
    + incrementarQuantidade()
    + decrementarQuantidade()
}

Venda "1..*" *-- "1" Item
Item "1" *-- "1" Produto
Estoque "0..*" o-- "1" Inventario
Inventario "1" -- "1" Produto




@enduml